//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinoba.business
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kinobaEntities : DbContext
    {
        public kinobaEntities()
            : base("name=kinobaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Profession> Professions { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<SpecialistProfessionLink> SpecialistProfessionLinks { get; set; }
        public virtual DbSet<Specialist> Specialists { get; set; }
        public virtual DbSet<SpecialistSchoolLink> SpecialistSchoolLinks { get; set; }
        public virtual DbSet<SpecialistMedia> SpecialistMedias { get; set; }
        public virtual DbSet<SpecialistPhoto> SpecialistPhotos { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
