//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinoba.business
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialistSchoolLink
    {
        public int Id { get; set; }
        public int SpecialistId { get; set; }
        public int SchoolId { get; set; }
    
        public virtual School School { get; set; }
        public virtual Specialist Specialist { get; set; }
    }
}
